FROM elixir:1.16
RUN apt-get update -y && \
        apt-get install -y \
        postgresql-client \
        inotify-tools \
        build-essential \
        git \
        libsqlite3-dev \
        libsodium-dev
RUN curl -fsSL https://deb.nodesource.com/setup_21.x | bash - &&\
        apt-get install -y nodejs


RUN npm install -g esbuild

RUN mkdir /app /archive
WORKDIR /app
RUN useradd -u 1000 rawwater -m && \
        chown -R rawwater:rawwater /app
USER rawwater:rawwater

RUN mix local.hex --force && mix local.rebar --force

COPY --chown=rawwater:rawwater mix.exs /app/mix.exs

# fine-grained access token with contents and metadata read-only perms on ctf_tickets_elixir
RUN mix deps.get && \
        mix deps.compile

COPY --chown=rawwater:rawwater assets/package.json /app/assets/package.json
COPY --chown=rawwater:rawwater assets/package-lock.json /app/assets/package-lock.json
RUN cd assets && npm install

COPY --chown=rawwater:rawwater . /app
CMD mix phx.server
